// src/lib/components/Header.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { Menu } from 'lucide-svelte';
  import type { Writable } from 'svelte/store';
  import { generateCSRFToken } from '$lib/utils/validation';
  import { announceToScreenReader } from '$lib/utils/accessibility';

  import MainNavigation from './layout/Header/Navigation/MainNavigation.svelte';
  import MobileNavigation from './layout/Header/Navigation/MobileNavigation.svelte';
  import GlobalSearch from './layout/Header/Search/GlobalSearch.svelte';
  import UserMenu from './layout/Header/UserMenu/UserMenu.svelte';

  interface User {
    id: number;
    username: string;
    email: string;
    full_name: string;
    avatar?: string;
    role: string;
  }

  export let variant: 'default' | 'compact' | 'minimal' = 'default';
  export let sidebarOpen: Writable<boolean>;
  export let toggleMobileMenu: (() => void) | undefined = undefined;
  export let user: User | null = null;
  export let unreadNotifications: number = 0;

  let isMobileMenuOpen = false;
  let isSearchOpen = false;
  let globalSearch: GlobalSearch;
  let csrfToken = '';
  let keyboardNavigation = false;

  $: currentPath = $page.url.pathname;

  onMount(() => {
    csrfToken = generateCSRFToken();

    // Global keyboard shortcuts
    const handleKeydown = (e: KeyboardEvent) => {
      if (e.metaKey || e.ctrlKey) {
        switch (e.key.toLowerCase()) {
          case 'k':
            e.preventDefault();
            globalSearch?.openSearch();
            break;
          case 'b':
            e.preventDefault();
            toggleSidebar();
            break;
        }
      }

      // Escape key handling
      if (e.key === 'Escape') {
        if (isMobileMenuOpen) {
          isMobileMenuOpen = false;
        }
      }

      // Tab navigation detection
      if (e.key === 'Tab') {
        keyboardNavigation = true;
        document.body.classList.add('keyboard-navigation');
      }
    };

    const handleMouseDown = () => {
      keyboardNavigation = false;
      document.body.classList.remove('keyboard-navigation');
    };

    document.addEventListener('keydown', handleKeydown);
    document.addEventListener('mousedown', handleMouseDown);

    return () => {
      document.removeEventListener('keydown', handleKeydown);
      document.removeEventListener('mousedown', handleMouseDown);
      csrfToken = '';
    };
  });

  function toggleSidebar() {
    sidebarOpen.update((open) => !open);
    announceToScreenReader($sidebarOpen ? 'Sidebar opened' : 'Sidebar closed');
  }

  function handleThemeToggle() {
    const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
    const newTheme = isDark ? 'light' : 'dark';

    document.documentElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('wakedock_theme', newTheme);

    announceToScreenReader(`Theme changed to ${newTheme} mode`);
  }

  function handleLogout() {
    // Implement logout logic
    announceToScreenReader('Signing out...');
    // Redirect to logout endpoint or clear auth state
  }
</script>

<header
  class="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700 sticky top-0 z-40"
  class:compact={variant === 'compact'}
>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Left Section: Logo + Navigation -->
      <div class="flex items-center space-x-8">
        <!-- Logo -->
        <div class="flex items-center space-x-4">
          <!-- Sidebar Toggle (when sidebar exists) -->
          <button
            type="button"
            class="p-2 rounded-md text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500 lg:hidden"
            on:click={toggleSidebar}
            aria-label="Toggle sidebar"
          >
            <Menu class="h-5 w-5" />
          </button>

          <!-- Brand -->
          <a href="/" class="flex items-center space-x-2">
            <img src="/logo.png" alt="WakeDock" class="h-8 w-8" />
            <span class="text-xl font-bold text-gray-900 dark:text-white">WakeDock</span>
          </a>
        </div>

        <!-- Desktop Navigation -->
        {#if variant !== 'minimal'}
          <MainNavigation {currentPath} />
        {/if}
      </div>

      <!-- Center Section: Search -->
      {#if variant === 'default'}
        <div class="flex-1 max-w-lg mx-8">
          <GlobalSearch bind:this={globalSearch} bind:isOpen={isSearchOpen} />
        </div>
      {/if}

      <!-- Right Section: User Actions -->
      <div class="flex items-center space-x-4">
        <!-- User Menu -->
        <UserMenu
          {user}
          {unreadNotifications}
          on:themeToggle={handleThemeToggle}
          on:logout={handleLogout}
        />

        <!-- Mobile Menu Toggle -->
        <button
          type="button"
          class="p-2 rounded-md text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500 lg:hidden mobile-haptic-feedback"
          on:click={toggleMobileMenu || (() => (isMobileMenuOpen = !isMobileMenuOpen))}
          aria-label="Toggle mobile menu"
          aria-expanded={isMobileMenuOpen}
        >
          <Menu class="h-5 w-5" />
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile Navigation -->
  {#if isMobileMenuOpen}
    <MobileNavigation {currentPath} on:close={() => (isMobileMenuOpen = false)} />
  {/if}
</header>

<style>
  .compact {
    @apply h-12;
  }

  .compact .h-16 {
    @apply h-12;
  }

  :global(.keyboard-navigation) :global(*:focus) {
    @apply outline-none ring-2 ring-green-500 ring-offset-2;
  }
</style>

// src/components/layout/header.tsx
'use client';

import { useState } from 'react';
import { useAuthStore } from '@/lib/stores/auth-store';
import { Menu, Search, User, Bell, Settings, LogOut } from 'lucide-react';

interface HeaderProps {
  sidebarOpen: boolean;
  onToggleMobileMenu: () => void;
}

export function Header({ sidebarOpen, onToggleMobileMenu }: HeaderProps) {
  const { user, logout } = useAuthStore();
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const handleLogout = async () => {
    await logout();
    setShowUserMenu(false);
  };

  return (
    <header className="header bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-4 lg:px-6 py-4 flex items-center justify-between">
      {/* Mobile menu button */}
      <div className="flex items-center gap-4">
        <button
          onClick={onToggleMobileMenu}
          className="lg:hidden p-2 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500"
          aria-label="Open mobile menu"
        >
          <Menu className="h-6 w-6" />
        </button>

        {/* Logo for mobile */}
        <div className="lg:hidden flex items-center">
          <img
            className="h-8 w-auto"
            src="/logo.svg"
            alt="WakeDock"
          />
          <span className="ml-2 text-xl font-bold text-gray-900 dark:text-white">
            WakeDock
          </span>
        </div>
      </div>

      {/* Search bar */}
      <div className="hidden md:block flex-1 max-w-lg mx-8">
        <div className="relative">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search className="h-5 w-5 text-gray-400" />
          </div>
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white dark:bg-gray-700 dark:border-gray-600 placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-primary-500 focus:border-primary-500 text-sm"
            placeholder="Search services, containers..."
          />
        </div>
      </div>

      {/* Right side */}
      <div className="flex items-center gap-4">
        {/* Search button for mobile */}
        <button className="md:hidden p-2 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700">
          <Search className="h-6 w-6" />
        </button>

        {/* Notifications */}
        <button className="p-2 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 relative">
          <Bell className="h-6 w-6" />
          <span className="absolute top-1 right-1 block h-2 w-2 rounded-full bg-red-400 ring-2 ring-white dark:ring-gray-800"></span>
        </button>

        {/* User menu */}
        <div className="relative">
          <button
            onClick={() => setShowUserMenu(!showUserMenu)}
            className="flex items-center gap-2 p-2 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700"
          >
            <div className="flex items-center gap-3">
              <div className="hidden sm:block text-right">
                <div className="text-sm font-medium text-gray-900 dark:text-white">
                  {user?.username || 'User'}
                </div>
                <div className="text-xs text-gray-500 dark:text-gray-400">
                  {user?.email}
                </div>
              </div>
              <div className="h-8 w-8 rounded-full bg-primary-600 flex items-center justify-center text-white text-sm font-medium">
                {user?.username?.[0]?.toUpperCase() || 'U'}
              </div>
            </div>
          </button>

          {/* User dropdown menu */}
          {showUserMenu && (
            <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-md shadow-lg ring-1 ring-black ring-opacity-5 z-50">
              <div className="py-1">
                <a
                  href="/profile"
                  className="flex items-center gap-2 px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  <User className="h-4 w-4" />
                  Profile
                </a>
                <a
                  href="/settings"
                  className="flex items-center gap-2 px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  <Settings className="h-4 w-4" />
                  Settings
                </a>
                <hr className="my-1 border-gray-200 dark:border-gray-600" />
                <button
                  onClick={handleLogout}
                  className="flex items-center gap-2 w-full px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 text-left"
                >
                  <LogOut className="h-4 w-4" />
                  Sign out
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
