// src/views/atoms/Modal.tsx
'use client'

import React, { useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { createPortal } from 'react-dom'
import { cn } from '@/lib/utils'

export interface ModalProps {
    isOpen: boolean
    onClose: () => void
    title?: string
    children: React.ReactNode
    size?: 'sm' | 'md' | 'lg' | 'xl' | 'full'
    variant?: 'default' | 'centered' | 'drawer'
    closeOnOverlayClick?: boolean
    closeOnEscape?: boolean
    showCloseButton?: boolean
    className?: string
    overlayClassName?: string
    contentClassName?: string
    persistent?: boolean
}

const Modal: React.FC<ModalProps> = ({
    isOpen,
    onClose,
    title,
    children,
    size = 'md',
    variant = 'default',
    closeOnOverlayClick = true,
    closeOnEscape = true,
    showCloseButton = true,
    className,
    overlayClassName,
    contentClassName,
    persistent = false,
}) => {
    const modalRef = useRef<HTMLDivElement>(null)
    const previousFocusRef = useRef<HTMLElement | null>(null)

    // Handle escape key
    useEffect(() => {
        const handleEscape = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && closeOnEscape && !persistent) {
                onClose()
            }
        }

        if (isOpen) {
            document.addEventListener('keydown', handleEscape)
            // Store previous focus
            previousFocusRef.current = document.activeElement as HTMLElement
            // Prevent body scroll
            document.body.style.overflow = 'hidden'
        }

        return () => {
            document.removeEventListener('keydown', handleEscape)
            if (isOpen) {
                document.body.style.overflow = 'unset'
            }
        }
    }, [isOpen, closeOnEscape, onClose, persistent])

    // Restore focus when modal closes
    useEffect(() => {
        if (!isOpen && previousFocusRef.current) {
            previousFocusRef.current.focus()
        }
    }, [isOpen])

    // Focus management
    useEffect(() => {
        if (isOpen && modalRef.current) {
            const focusableElements = modalRef.current.querySelectorAll(
                'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
            )
            const firstFocusableElement = focusableElements[0] as HTMLElement
            const lastFocusableElement = focusableElements[focusableElements.length - 1] as HTMLElement

            const handleTabKeyPress = (e: KeyboardEvent) => {
                if (e.key === 'Tab') {
                    if (e.shiftKey) {
                        if (document.activeElement === firstFocusableElement) {
                            lastFocusableElement?.focus()
                            e.preventDefault()
                        }
                    } else {
                        if (document.activeElement === lastFocusableElement) {
                            firstFocusableElement?.focus()
                            e.preventDefault()
                        }
                    }
                }
            }

            modalRef.current.addEventListener('keydown', handleTabKeyPress)
            firstFocusableElement?.focus()

            return () => {
                modalRef.current?.removeEventListener('keydown', handleTabKeyPress)
            }
        }
    }, [isOpen])

    const handleOverlayClick = (e: React.MouseEvent) => {
        if (e.target === e.currentTarget && closeOnOverlayClick && !persistent) {
            onClose()
        }
    }

    const getSizeClasses = () => {
        switch (size) {
            case 'sm':
                return 'max-w-sm'
            case 'md':
                return 'max-w-md'
            case 'lg':
                return 'max-w-lg'
            case 'xl':
                return 'max-w-xl'
            case 'full':
                return 'max-w-full mx-4'
            default:
                return 'max-w-md'
        }
    }

    const getVariantClasses = () => {
        switch (variant) {
            case 'centered':
                return 'flex items-center justify-center min-h-screen p-4'
            case 'drawer':
                return 'flex items-start justify-end min-h-screen'
            default:
                return 'flex items-center justify-center min-h-screen p-4'
        }
    }

    const getContentVariantClasses = () => {
        switch (variant) {
            case 'drawer':
                return 'h-full w-full max-w-md rounded-l-2xl'
            default:
                return 'w-full rounded-2xl'
        }
    }

    const overlayVariants = {
        hidden: { opacity: 0 },
        visible: { opacity: 1 },
        exit: { opacity: 0 }
    }

    const contentVariants = {
        hidden: {
            opacity: 0,
            scale: variant === 'drawer' ? 1 : 0.95,
            x: variant === 'drawer' ? 300 : 0,
            y: variant === 'drawer' ? 0 : 10
        },
        visible: {
            opacity: 1,
            scale: 1,
            x: 0,
            y: 0,
            transition: {
                type: 'spring',
                stiffness: 300,
                damping: 30
            }
        },
        exit: {
            opacity: 0,
            scale: variant === 'drawer' ? 1 : 0.95,
            x: variant === 'drawer' ? 300 : 0,
            y: variant === 'drawer' ? 0 : 10,
            transition: {
                duration: 0.2,
                ease: 'easeInOut'
            }
        }
    }

    if (!isOpen) return null

    const modalContent = (
        <AnimatePresence mode="wait">
            <motion.div
                className={cn(
                    'fixed inset-0 z-50 bg-black/50 backdrop-blur-sm',
                    getVariantClasses(),
                    overlayClassName
                )}
                variants={overlayVariants}
                initial="hidden"
                animate="visible"
                exit="exit"
                onClick={handleOverlayClick}
                aria-modal="true"
                role="dialog"
                aria-labelledby={title ? 'modal-title' : undefined}
            >
                <motion.div
                    ref={modalRef}
                    className={cn(
                        'relative bg-white dark:bg-gray-900 shadow-2xl',
                        'border border-gray-200 dark:border-gray-700',
                        getSizeClasses(),
                        getContentVariantClasses(),
                        'max-h-[90vh] overflow-hidden',
                        contentClassName
                    )}
                    variants={contentVariants}
                    initial="hidden"
                    animate="visible"
                    exit="exit"
                    onClick={(e) => e.stopPropagation()}
                >
                    {/* Header */}
                    {(title || showCloseButton) && (
                        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
                            {title && (
                                <h2 id="modal-title" className="text-lg font-semibold text-gray-900 dark:text-white">
                                    {title}
                                </h2>
                            )}
                            {showCloseButton && (
                                <motion.button
                                    onClick={onClose}
                                    disabled={persistent}
                                    className={cn(
                                        'p-2 rounded-lg transition-colors duration-200',
                                        'hover:bg-gray-100 dark:hover:bg-gray-800',
                                        'focus:outline-none focus:ring-2 focus:ring-primary-500',
                                        'disabled:opacity-50 disabled:cursor-not-allowed'
                                    )}
                                    whileHover={{ scale: 1.05 }}
                                    whileTap={{ scale: 0.95 }}
                                    aria-label="Close modal"
                                >
                                    <svg
                                        className="w-5 h-5 text-gray-500 dark:text-gray-400"
                                        fill="none"
                                        stroke="currentColor"
                                        viewBox="0 0 24 24"
                                    >
                                        <path
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                            strokeWidth={2}
                                            d="M6 18L18 6M6 6l12 12"
                                        />
                                    </svg>
                                </motion.button>
                            )}
                        </div>
                    )}

                    {/* Content */}
                    <div className={cn(
                        'p-6 overflow-y-auto',
                        variant === 'drawer' ? 'h-full' : 'max-h-[70vh]',
                        className
                    )}>
                        {children}
                    </div>

                    {/* Glassmorphism effect */}
                    <div
                        className="absolute inset-0 bg-gradient-to-br from-white/10 to-transparent pointer-events-none rounded-2xl"
                        aria-hidden="true"
                    />
                </motion.div>
            </motion.div>
        </AnimatePresence>
    )

    // Render modal in portal
    return typeof document !== 'undefined'
        ? createPortal(modalContent, document.body)
        : null
}

export { Modal }

// Hook for modal state management
export const useModal = (initialState = false) => {
    const [isOpen, setIsOpen] = React.useState(initialState)

    const openModal = React.useCallback(() => setIsOpen(true), [])
    const closeModal = React.useCallback(() => setIsOpen(false), [])
    const toggleModal = React.useCallback(() => setIsOpen(prev => !prev), [])

    return {
        isOpen,
        openModal,
        closeModal,
        toggleModal,
        setIsOpen
    }
}

// src/lib/components/ui/organisms/Modal.svelte
<!-- Base Modal Component -->
<script lang="ts">
  import { createEventDispatcher, onMount, onDestroy, tick } from 'svelte';
  import { manageFocus, announceToScreenReader, trapFocus } from '$lib/utils/accessibility';
  import { colors } from '$lib/design-system/tokens';

  export let open: boolean = false;
  export let size: 'sm' | 'md' | 'lg' | 'xl' | 'full' = 'md';
  export let persistent: boolean = false; // Prevent closing on backdrop click
  export let showCloseButton: boolean = true;
  export let title: string = '';
  export let closeOnEscape: boolean = true;
  export let ariaLabel: string = '';
  export let ariaDescribedBy: string = '';
  export let role: 'dialog' | 'alertdialog' = 'dialog';

  const dispatch = createEventDispatcher<{
    close: void;
    open: void;
  }>();

  // Size classes
  const sizeClasses = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-4xl',
    full: 'max-w-full mx-4',
  };

  let modalElement: HTMLDivElement;
  let previouslyFocusedElement: HTMLElement | null = null;
  let focusTrap: { destroy: () => void } | null = null;

  // Generate unique IDs for accessibility
  const titleId = `modal-title-${Math.random().toString(36).substr(2, 9)}`;
  const descriptionId = `modal-description-${Math.random().toString(36).substr(2, 9)}`;

  onMount(() => {
    // Only run in browser (not during SSR)
    if (typeof window !== 'undefined' && typeof document !== 'undefined') {
      // Global escape key handling
      const handleKeydown = (event: KeyboardEvent) => {
        if (open && closeOnEscape && event.key === 'Escape') {
          handleClose();
        }
      };

      document.addEventListener('keydown', handleKeydown);

      return () => {
        document.removeEventListener('keydown', handleKeydown);
      };
    }
  });

  onDestroy(() => {
    // Restore focus when component is destroyed
    if (previouslyFocusedElement) {
      manageFocus(previouslyFocusedElement);
    }

    // Clean up focus trap
    if (focusTrap) {
      focusTrap.destroy();
    }
  });

  // Watch for modal open/close changes
  $: if (open) {
    handleOpen();
  } else {
    handleCloseCleanup();
  }

  async function handleOpen() {
    await tick();

    // Store previously focused element
    previouslyFocusedElement = document.activeElement as HTMLElement;

    // Prevent body scroll
    document.body.style.overflow = 'hidden';

    // Set up focus trap
    if (modalElement) {
      focusTrap = trapFocus(modalElement);

      // Focus the first focusable element or the modal itself
      const firstFocusable = modalElement.querySelector(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      if (firstFocusable) {
        manageFocus(firstFocusable as HTMLElement);
      } else {
        manageFocus(modalElement);
      }
    }

    // Announce modal opening to screen readers
    announceToScreenReader(
      `${role === 'alertdialog' ? 'Alert dialog' : 'Dialog'} opened: ${title || 'Modal dialog'}`
    );

    dispatch('open');
  }

  function handleCloseCleanup() {
    // Restore body scroll
    document.body.style.overflow = '';

    // Clean up focus trap
    if (focusTrap) {
      focusTrap.destroy();
      focusTrap = null;
    }

    // Restore focus to previously focused element
    if (previouslyFocusedElement) {
      manageFocus(previouslyFocusedElement);
      previouslyFocusedElement = null;
    }
  }

  const handleBackdropClick = (event: MouseEvent) => {
    if (!persistent && event.target === event.currentTarget) {
      handleClose();
    }
  };

  const handleBackdropKeydown = (event: KeyboardEvent) => {
    if (!persistent && event.target === event.currentTarget && (event.key === 'Enter' || event.key === ' ')) {
      event.preventDefault();
      handleClose();
    }
  };

  const handleClose = () => {
    if (open) {
      open = false;
      dispatch('close');
    }
  };
</script>

{#if open}
  <!-- Backdrop -->
  <div
    class="fixed inset-0 bg-secondary-600 bg-opacity-50 overflow-y-auto h-full w-full z-50 flex items-center justify-center p-4"
    on:click={handleBackdropClick}
    on:keydown={handleBackdropKeydown}
    bind:this={modalElement}
    {role}
    aria-modal="true"
    aria-labelledby={title ? titleId : ariaLabel ? undefined : 'modal-title'}
    aria-describedby={ariaDescribedBy || descriptionId}
    aria-label={ariaLabel}
    tabindex="-1"
  >
    <!-- Modal Content -->
    <div
      class="relative bg-white rounded-lg shadow-xl {sizeClasses[
        size
      ]} w-full max-h-full overflow-hidden"
      role="document"
      on:click|stopPropagation
    >
      <!-- Header -->
      {#if title || showCloseButton || $$slots.header}
        <div class="flex items-center justify-between p-6 border-b border-secondary-200">
          <div class="flex items-center">
            {#if $$slots.header}
              <slot name="header" />
            {:else if title}
              <h3 class="text-lg font-medium text-secondary-900">
                {title}
              </h3>
            {/if}
          </div>

          {#if showCloseButton}
            <button
              type="button"
              class="text-secondary-400 hover:text-secondary-600 focus:outline-none focus:text-secondary-600 transition ease-in-out duration-150"
              on:click={handleClose}
              aria-label="Close modal"
            >
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          {/if}
        </div>
      {/if}

      <!-- Body -->
      <div class="p-6 overflow-y-auto max-h-96">
        <slot />
      </div>

      <!-- Footer -->
      {#if $$slots.footer}
        <div class="flex items-center justify-end px-6 py-4 bg-secondary-50 border-t border-secondary-200">
          <slot name="footer" />
        </div>
      {/if}
    </div>
  </div>
{/if}
